import './globals.css'
import { type Metadata } from 'next'
import { Open_Sans } from 'next/font/google'

import { cn } from '@/lib/utils'

import { Providers } from './providers'

const font = Open_Sans({ subsets: ['latin', 'cyrillic'] })

export const metadata: Metadata = {
  title: 'Team Chat App',
  description: 'Generated by create next app',
}

const RootLayout: NextLayout = ({ children }) => (
  <html lang="en" suppressHydrationWarning>
    <body className={cn(font.className, 'bg-white dark:bg-[#313338]')} suppressHydrationWarning>
      <Providers>{children}</Providers>
    </body>
  </html>
)

export default RootLayout
